### ISSUE TITLE
Running search_task again does not trigger download again

### ISSUE THREAD

**Issue by dapurv5** [tangg555/acl-anthology-helper#2]
If I run the search_task again, it will not trigger another download.

**Comment by tangg555** [comment]
Hi, this is because all the conference content gets downloaded during the basic task run. I’ve added caching to keep track of what’s already been done. If you want to redownload everything, just delete the cache directory at tasks/cache or disable caching by setting cache_enable=False. Then, rerun python basic_task.py. I’ve also updated the README with this info.
